// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package postgres

import (
	"context"
	"database/sql"
	"time"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM se_audit_logs
`

func (q *Queries) CountAuditLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchAuditLogs = `-- name: CountSearchAuditLogs :one
SELECT COUNT(*)
FROM se_audit_logs a
LEFT JOIN core_users u ON a.user_id = u.id
WHERE
    ($1 = '' OR u.email ILIKE $1) AND
    ($2 = '' OR a.action = $2) AND
    ($3 = '' OR a.entity = $3)
`

type CountSearchAuditLogsParams struct {
	Column1 interface{}
	Column2 interface{}
	Column3 interface{}
}

func (q *Queries) CountSearchAuditLogs(ctx context.Context, arg CountSearchAuditLogsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchAuditLogs, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO se_audit_logs (user_id, action, entity, entity_id, details, ip_address)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAuditLogParams struct {
	UserID    sql.NullInt32
	Action    string
	Entity    string
	EntityID  sql.NullString
	Details   sql.NullString
	IpAddress sql.NullString
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, createAuditLog,
		arg.UserID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Details,
		arg.IpAddress,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT a.id, a.user_id, a.action, a.entity, a.entity_id, a.details, a.ip_address, a.created_at, u.email
FROM se_audit_logs a
LEFT JOIN core_users u ON a.user_id = u.id
ORDER BY a.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int32
	Offset int32
}

type ListAuditLogsRow struct {
	ID        int32
	UserID    sql.NullInt32
	Action    string
	Entity    string
	EntityID  sql.NullString
	Details   sql.NullString
	IpAddress sql.NullString
	CreatedAt time.Time
	Email     sql.NullString
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogsRow
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Entity,
			&i.EntityID,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAuditLogs = `-- name: SearchAuditLogs :many
SELECT a.id, a.user_id, a.action, a.entity, a.entity_id, a.details, a.ip_address, a.created_at, u.email
FROM se_audit_logs a
LEFT JOIN core_users u ON a.user_id = u.id
WHERE
    ($3 = '' OR u.email ILIKE $3) AND
    ($4 = '' OR a.action = $4) AND
    ($5 = '' OR a.entity = $5)
ORDER BY a.created_at DESC
LIMIT $1 OFFSET $2
`

type SearchAuditLogsParams struct {
	Limit   int32
	Offset  int32
	Column3 interface{}
	Column4 interface{}
	Column5 interface{}
}

type SearchAuditLogsRow struct {
	ID        int32
	UserID    sql.NullInt32
	Action    string
	Entity    string
	EntityID  sql.NullString
	Details   sql.NullString
	IpAddress sql.NullString
	CreatedAt time.Time
	Email     sql.NullString
}

func (q *Queries) SearchAuditLogs(ctx context.Context, arg SearchAuditLogsParams) ([]SearchAuditLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchAuditLogs,
		arg.Limit,
		arg.Offset,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAuditLogsRow
	for rows.Next() {
		var i SearchAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Entity,
			&i.EntityID,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
