// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: se_balance_types.sql

package postgres

import (
	"context"
)

const countBalanceTypes = `-- name: CountBalanceTypes :one
SELECT COUNT(*) FROM se_balance_types
`

func (q *Queries) CountBalanceTypes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBalanceTypes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBalanceType = `-- name: CreateBalanceType :exec
INSERT INTO se_balance_types (
    code,
    short_description,
    column_indicator,
    full_description,
    validation_rule
) VALUES ($1, $2, $3, $4, $5)
`

type CreateBalanceTypeParams struct {
	Code             string
	ShortDescription string
	ColumnIndicator  string
	FullDescription  string
	ValidationRule   string
}

func (q *Queries) CreateBalanceType(ctx context.Context, arg CreateBalanceTypeParams) error {
	_, err := q.db.ExecContext(ctx, createBalanceType,
		arg.Code,
		arg.ShortDescription,
		arg.ColumnIndicator,
		arg.FullDescription,
		arg.ValidationRule,
	)
	return err
}

const deleteAllBalanceTypes = `-- name: DeleteAllBalanceTypes :exec
DELETE FROM se_balance_types
`

func (q *Queries) DeleteAllBalanceTypes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllBalanceTypes)
	return err
}

const deleteBalanceType = `-- name: DeleteBalanceType :exec
DELETE FROM se_balance_types
WHERE code = $1
`

func (q *Queries) DeleteBalanceType(ctx context.Context, code string) error {
	_, err := q.db.ExecContext(ctx, deleteBalanceType, code)
	return err
}

const getBalanceType = `-- name: GetBalanceType :one
SELECT code, short_description, column_indicator, full_description, validation_rule, created_at FROM se_balance_types
WHERE code = $1
`

func (q *Queries) GetBalanceType(ctx context.Context, code string) (BalanceType, error) {
	row := q.db.QueryRowContext(ctx, getBalanceType, code)
	var i BalanceType
	err := row.Scan(
		&i.Code,
		&i.ShortDescription,
		&i.ColumnIndicator,
		&i.FullDescription,
		&i.ValidationRule,
		&i.CreatedAt,
	)
	return i, err
}

const listBalanceTypes = `-- name: ListBalanceTypes :many
SELECT code, short_description, column_indicator, full_description, validation_rule, created_at FROM se_balance_types
ORDER BY code
`

func (q *Queries) ListBalanceTypes(ctx context.Context) ([]BalanceType, error) {
	rows, err := q.db.QueryContext(ctx, listBalanceTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BalanceType
	for rows.Next() {
		var i BalanceType
		if err := rows.Scan(
			&i.Code,
			&i.ShortDescription,
			&i.ColumnIndicator,
			&i.FullDescription,
			&i.ValidationRule,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBalanceType = `-- name: UpdateBalanceType :one
UPDATE se_balance_types
SET short_description = $2,
    column_indicator = $3,
    full_description = $4,
    validation_rule = $5
WHERE code = $1
RETURNING code, short_description, column_indicator, full_description, validation_rule, created_at
`

type UpdateBalanceTypeParams struct {
	Code             string
	ShortDescription string
	ColumnIndicator  string
	FullDescription  string
	ValidationRule   string
}

func (q *Queries) UpdateBalanceType(ctx context.Context, arg UpdateBalanceTypeParams) (BalanceType, error) {
	row := q.db.QueryRowContext(ctx, updateBalanceType,
		arg.Code,
		arg.ShortDescription,
		arg.ColumnIndicator,
		arg.FullDescription,
		arg.ValidationRule,
	)
	var i BalanceType
	err := row.Scan(
		&i.Code,
		&i.ShortDescription,
		&i.ColumnIndicator,
		&i.FullDescription,
		&i.ValidationRule,
		&i.CreatedAt,
	)
	return i, err
}
