// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: se_expected_balances.sql

package postgres

import (
	"context"
)

const countExpectedBalances = `-- name: CountExpectedBalances :one
SELECT COUNT(*) FROM se_expected_balances
WHERE 
    ($1::text = '' OR account_number ILIKE $1 OR account_name ILIKE $1)
    AND
    ($2::text = '' OR expected_balance_type = $2)
`

type CountExpectedBalancesParams struct {
	Column1 string
	Column2 string
}

func (q *Queries) CountExpectedBalances(ctx context.Context, arg CountExpectedBalancesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countExpectedBalances, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllExpectedBalances = `-- name: DeleteAllExpectedBalances :exec
DELETE FROM se_expected_balances
`

func (q *Queries) DeleteAllExpectedBalances(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllExpectedBalances)
	return err
}

const deleteExpectedBalance = `-- name: DeleteExpectedBalance :exec
DELETE FROM se_expected_balances
WHERE account_number = $1
`

func (q *Queries) DeleteExpectedBalance(ctx context.Context, accountNumber string) error {
	_, err := q.db.ExecContext(ctx, deleteExpectedBalance, accountNumber)
	return err
}

const getExpectedBalance = `-- name: GetExpectedBalance :one
SELECT id, account_number, account_name, expected_balance_type, balance_type_code, created_at, updated_at FROM se_expected_balances
WHERE account_number = $1 LIMIT 1
`

func (q *Queries) GetExpectedBalance(ctx context.Context, accountNumber string) (ExpectedBalance, error) {
	row := q.db.QueryRowContext(ctx, getExpectedBalance, accountNumber)
	var i ExpectedBalance
	err := row.Scan(
		&i.ID,
		&i.AccountNumber,
		&i.AccountName,
		&i.ExpectedBalanceType,
		&i.BalanceTypeCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllExpectedBalances = `-- name: ListAllExpectedBalances :many
SELECT id, account_number, account_name, expected_balance_type, balance_type_code, created_at, updated_at FROM se_expected_balances
ORDER BY account_number
`

func (q *Queries) ListAllExpectedBalances(ctx context.Context) ([]ExpectedBalance, error) {
	rows, err := q.db.QueryContext(ctx, listAllExpectedBalances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpectedBalance
	for rows.Next() {
		var i ExpectedBalance
		if err := rows.Scan(
			&i.ID,
			&i.AccountNumber,
			&i.AccountName,
			&i.ExpectedBalanceType,
			&i.BalanceTypeCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpectedBalances = `-- name: ListExpectedBalances :many
SELECT id, account_number, account_name, expected_balance_type, balance_type_code, created_at, updated_at FROM se_expected_balances
WHERE 
    ($1::text = '' OR account_number ILIKE $1 OR account_name ILIKE $1)
    AND
    ($2::text = '' OR expected_balance_type = $2)
ORDER BY account_number
LIMIT $3 OFFSET $4
`

type ListExpectedBalancesParams struct {
	Column1 string
	Column2 string
	Limit   int32
	Offset  int32
}

func (q *Queries) ListExpectedBalances(ctx context.Context, arg ListExpectedBalancesParams) ([]ExpectedBalance, error) {
	rows, err := q.db.QueryContext(ctx, listExpectedBalances,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpectedBalance
	for rows.Next() {
		var i ExpectedBalance
		if err := rows.Scan(
			&i.ID,
			&i.AccountNumber,
			&i.AccountName,
			&i.ExpectedBalanceType,
			&i.BalanceTypeCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExpectedBalance = `-- name: UpsertExpectedBalance :one
INSERT INTO se_expected_balances (account_number, account_name, expected_balance_type)
VALUES ($1, $2, $3)
ON CONFLICT (account_number) DO UPDATE
SET account_name = EXCLUDED.account_name,
    expected_balance_type = EXCLUDED.expected_balance_type,
    updated_at = NOW()
RETURNING id, account_number, account_name, expected_balance_type, balance_type_code, created_at, updated_at
`

type UpsertExpectedBalanceParams struct {
	AccountNumber       string
	AccountName         string
	ExpectedBalanceType string
}

func (q *Queries) UpsertExpectedBalance(ctx context.Context, arg UpsertExpectedBalanceParams) (ExpectedBalance, error) {
	row := q.db.QueryRowContext(ctx, upsertExpectedBalance, arg.AccountNumber, arg.AccountName, arg.ExpectedBalanceType)
	var i ExpectedBalance
	err := row.Scan(
		&i.ID,
		&i.AccountNumber,
		&i.AccountName,
		&i.ExpectedBalanceType,
		&i.BalanceTypeCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
