// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"database/sql"
	"time"
)

type AuditLog struct {
	ID        int32
	UserID    sql.NullInt32
	Action    string
	Entity    string
	EntityID  sql.NullString
	Details   sql.NullString
	IpAddress sql.NullString
	CreatedAt time.Time
}

type BalanceType struct {
	Code             string
	ShortDescription string
	ColumnIndicator  string
	FullDescription  string
	ValidationRule   string
	CreatedAt        time.Time
}

type ExpectedBalance struct {
	ID                  int32
	AccountNumber       string
	AccountName         string
	ExpectedBalanceType string
	BalanceTypeCode     sql.NullString
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type ProcessedRecord struct {
	ID                  int32
	UploadID            int32
	AccountNumber       string
	AccountName         string
	Balance             string
	ExpectedRuleAccount sql.NullString
	ExpectedBalanceType sql.NullString
	BalanceTypeCode     sql.NullString
	IsCorrect           bool
	CreatedAt           time.Time
}

type Upload struct {
	ID         int32
	Filename   string
	Label      sql.NullString
	UploadDate time.Time
	Status     string
}
