// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: se_uploads.sql

package postgres

import (
	"context"
	"database/sql"
)

const countUploads = `-- name: CountUploads :one
SELECT COUNT(*) FROM se_uploads
`

func (q *Queries) CountUploads(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUploads)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProcessedRecord = `-- name: CreateProcessedRecord :one
INSERT INTO se_processed_records (
    upload_id, account_number, account_name, balance, expected_rule_account, expected_balance_type, is_correct
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, upload_id, account_number, account_name, balance, expected_rule_account, expected_balance_type, balance_type_code, is_correct, created_at
`

type CreateProcessedRecordParams struct {
	UploadID            int32
	AccountNumber       string
	AccountName         string
	Balance             string
	ExpectedRuleAccount sql.NullString
	ExpectedBalanceType sql.NullString
	IsCorrect           bool
}

func (q *Queries) CreateProcessedRecord(ctx context.Context, arg CreateProcessedRecordParams) (ProcessedRecord, error) {
	row := q.db.QueryRowContext(ctx, createProcessedRecord,
		arg.UploadID,
		arg.AccountNumber,
		arg.AccountName,
		arg.Balance,
		arg.ExpectedRuleAccount,
		arg.ExpectedBalanceType,
		arg.IsCorrect,
	)
	var i ProcessedRecord
	err := row.Scan(
		&i.ID,
		&i.UploadID,
		&i.AccountNumber,
		&i.AccountName,
		&i.Balance,
		&i.ExpectedRuleAccount,
		&i.ExpectedBalanceType,
		&i.BalanceTypeCode,
		&i.IsCorrect,
		&i.CreatedAt,
	)
	return i, err
}

const createUpload = `-- name: CreateUpload :one
INSERT INTO se_uploads (filename, label, status)
VALUES ($1, $2, $3)
RETURNING id, filename, label, upload_date, status
`

type CreateUploadParams struct {
	Filename string
	Label    sql.NullString
	Status   string
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error) {
	row := q.db.QueryRowContext(ctx, createUpload, arg.Filename, arg.Label, arg.Status)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Label,
		&i.UploadDate,
		&i.Status,
	)
	return i, err
}

const getLastUpload = `-- name: GetLastUpload :one
SELECT id, filename, label, upload_date, status FROM se_uploads
ORDER BY upload_date DESC
LIMIT 1
`

func (q *Queries) GetLastUpload(ctx context.Context) (Upload, error) {
	row := q.db.QueryRowContext(ctx, getLastUpload)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Label,
		&i.UploadDate,
		&i.Status,
	)
	return i, err
}

const getUpload = `-- name: GetUpload :one
SELECT id, filename, label, upload_date, status FROM se_uploads
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUpload(ctx context.Context, id int32) (Upload, error) {
	row := q.db.QueryRowContext(ctx, getUpload, id)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Label,
		&i.UploadDate,
		&i.Status,
	)
	return i, err
}

const listProcessedRecordsByUpload = `-- name: ListProcessedRecordsByUpload :many
SELECT id, upload_id, account_number, account_name, balance, expected_rule_account, expected_balance_type, balance_type_code, is_correct, created_at FROM se_processed_records
WHERE upload_id = $1
ORDER BY account_number
`

func (q *Queries) ListProcessedRecordsByUpload(ctx context.Context, uploadID int32) ([]ProcessedRecord, error) {
	rows, err := q.db.QueryContext(ctx, listProcessedRecordsByUpload, uploadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProcessedRecord
	for rows.Next() {
		var i ProcessedRecord
		if err := rows.Scan(
			&i.ID,
			&i.UploadID,
			&i.AccountNumber,
			&i.AccountName,
			&i.Balance,
			&i.ExpectedRuleAccount,
			&i.ExpectedBalanceType,
			&i.BalanceTypeCode,
			&i.IsCorrect,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploads = `-- name: ListUploads :many
SELECT id, filename, label, upload_date, status FROM se_uploads
ORDER BY upload_date DESC
LIMIT $1 OFFSET $2
`

type ListUploadsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUploads(ctx context.Context, arg ListUploadsParams) ([]Upload, error) {
	rows, err := q.db.QueryContext(ctx, listUploads, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Upload
	for rows.Next() {
		var i Upload
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Label,
			&i.UploadDate,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUploadStatus = `-- name: UpdateUploadStatus :exec
UPDATE se_uploads
SET status = $2
WHERE id = $1
`

type UpdateUploadStatusParams struct {
	ID     int32
	Status string
}

func (q *Queries) UpdateUploadStatus(ctx context.Context, arg UpdateUploadStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUploadStatus, arg.ID, arg.Status)
	return err
}
